#!/usr/bin/env python3
"""Generate skills/README.md from each skill's Related Files section.

Reads all SKILL.md files under skills/ and produces a README.md that contains:
- a skill index table
- a complete workflow reference table with back-references to skills
- a complete util reference table with back-references to skills
- a maintenance note

Usage:
    python3 skills/scripts/generate_skill_index.py

The script is idempotent; run it whenever workflows/utils or skill contents change.
"""

from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Dict, List, Tuple

import yaml

ROOT = Path(__file__).resolve().parents[2]
SKILLS_DIR = ROOT / "skills"
WORKFLOWS_DIR = ROOT / ".github" / "workflows"
UTILS_DIR = ROOT / ".github" / "utils"
README_PATH = SKILLS_DIR / "README.md"

WORKFLOW_RE = re.compile(r"\.github/workflows/([\w.-]+\.(?:yml|yaml))")
UTIL_RE = re.compile(r"\.github/utils/([\w_.-]+)")


def find_skill_files(base: Path) -> List[Path]:
    """Find all SKILL.md files under base."""
    return sorted(base.rglob("SKILL.md"))


def parse_front_matter(text: str) -> dict:
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    return yaml.safe_load(text[3:end]) or {}


def extract_references(text: str) -> Tuple[List[str], List[str]]:
    """Return (workflows, utils) referenced in a SKILL.md body."""
    workflows = sorted({m.group(1) for m in WORKFLOW_RE.finditer(text)})
    utils = sorted({m.group(1) for m in UTIL_RE.finditer(text)})
    return workflows, utils


def load_skills() -> List[dict]:
    skills: List[dict] = []
    for path in find_skill_files(SKILLS_DIR):
        rel_dir = path.parent.relative_to(SKILLS_DIR)
        skill_link = str(rel_dir / "SKILL.md")
        text = path.read_text()
        fm = parse_front_matter(text)
        workflows, utils = extract_references(text)
        skills.append({
            "name": fm.get("name", rel_dir.name),
            "description": fm.get("description", "").replace("\n", " ").strip(),
            "link": skill_link,
            "dir": rel_dir,
            "workflows": workflows,
            "utils": utils,
        })
    return skills


def build_reference_map(skills: List[dict]) -> Tuple[Dict[str, List[str]], Dict[str, List[str]]]:
    """Return (workflow -> skill names, util -> skill names)."""
    wf_map: Dict[str, List[str]] = {}
    ut_map: Dict[str, List[str]] = {}
    for s in skills:
        for w in s["workflows"]:
            wf_map.setdefault(w, []).append(s["name"])
        for u in s["utils"]:
            ut_map.setdefault(u, []).append(s["name"])
    return wf_map, ut_map


def key_files_for_skill(skill: dict, limit: int = 4) -> str:
    """Return a concise comma-separated list of representative files."""
    candidates = []
    for w in skill["workflows"]:
        candidates.append(f"`{w}`")
        if len(candidates) >= limit:
            break
    for u in skill["utils"]:
        candidates.append(f"`{u}`")
        if len(candidates) >= limit:
            break
    return ", ".join(candidates[:limit]) if candidates else "_no files referenced_"


def render_readme(skills: List[dict], wf_map: Dict[str, List[str]], ut_map: Dict[str, List[str]]) -> str:
    all_workflows = sorted(p.name for p in WORKFLOWS_DIR.iterdir() if p.suffix in (".yml", ".yaml"))
    all_utils = sorted(p.name for p in UTILS_DIR.iterdir() if p.is_file() and not p.name.startswith("__"))

    lines: List[str] = [
        "# apecloud-cd Skill Index",
        "",
        "This directory organizes Codex skills by **business domain**. Each skill maps to a tightly related group of `.github/workflows/*.yml` and `.github/utils/*.sh` files.",
        "",
        "> The project only cares about the `.github/utils` and `.github/workflows` directories, so the skill design is scoped to these two directories only.",
        "",
        "This README is generated by `skills/scripts/generate_skill_index.py`. Do not edit it manually; run the generator instead.",
        "",
        "## Choose a Skill by Problem Domain",
        "",
        "| Skill | Purpose | Key files |",
        "|---|---|---|",
    ]

    # Sort skills alphabetically by name for stable output
    for s in sorted(skills, key=lambda x: x["name"]):
        desc = " ".join(s["description"].split())
        lines.append(f"| [{s['name']}]({s['link']}) | {desc} | {key_files_for_skill(s)} |")

    lines.extend([
        "",
        "## Workflow Reference",
        "",
        f"All `{len(all_workflows)}` workflows under `.github/workflows/` and the skills that reference them.",
        "",
        "| Workflow | Referenced by skills |",
        "|---|---|",
    ])
    for w in all_workflows:
        refs = ", ".join(f"[{n}]({skill_link(n, skills)})" for n in sorted(wf_map.get(w, []))) or "_not referenced_"
        lines.append(f"| `{w}` | {refs} |")

    lines.extend([
        "",
        "## Util Reference",
        "",
        f"All `{len(all_utils)}` files under `.github/utils/` and the skills that reference them.",
        "",
        "| Util | Referenced by skills |",
        "|---|---|",
    ])
    for u in all_utils:
        refs = ", ".join(f"[{n}]({skill_link(n, skills)})" for n in sorted(ut_map.get(u, []))) or "_not referenced_"
        lines.append(f"| `{u}` | {refs} |")

    lines.extend([
        "",
        "## Maintaining This Index",
        "",
        "1. Add or update a skill by editing the corresponding `SKILL.md` under `skills/`.",
        "2. Run `python3 skills/scripts/generate_skill_index.py` to regenerate this README.",
        "3. Run `python3 skills/scripts/check_skill_coverage.py` to verify every workflow and util is referenced by at least one skill.",
        "",
    ])

    return "\n".join(lines) + "\n"


def skill_link(name: str, skills: List[dict]) -> str:
    for s in skills:
        if s["name"] == name:
            return s["link"]
    return "#"


def main() -> None:
    skills = load_skills()
    wf_map, ut_map = build_reference_map(skills)
    readme = render_readme(skills, wf_map, ut_map)
    README_PATH.write_text(readme)
    print(f"Generated {README_PATH}")
    print(f"  skills: {len(skills)}")
    print(f"  workflows referenced: {len(wf_map)}")
    print(f"  utils referenced: {len(ut_map)}")


if __name__ == "__main__":
    main()
