name: Cloud E2E Schedule

on:
  schedule:
    - cron: '30 18 * * 0-4' # Runs at 02:30 UTC on Mon to Friday

jobs:
  e2e-test:
    uses: ./.github/workflows/trigger-workflow.yml
    with:
      GITHUB_REPO: "apecloud/apecloud-cd"
      BRANCH_NAME: "main"
      WORKFLOW_ID: "cloud-e2e.yml"
      APECD_REF: "main"
      EXTRA_ARGS: "TEST_TYPE=openapi-test|adminapi-test|engine-test#TEST_ENGINES=mysql#CLOUD_ENV_NAME=dev#CLOUD_BRANCH=main#GO_VERSION=1.22#CURRENT_VERSION=${{ vars.CURRENT_RELEASE_VERSION }}"
    secrets: inherit
