name: Cloud E2E Schedule

on:
  schedule:
    - cron: '0 17 * * 0-4' # Runs at 01:00 UTC on Mon to Friday

jobs:
  e2e-test:
    uses: ./.github/workflows/trigger-workflow.yml
    with:
      GITHUB_REPO: "apecloud/apecloud-cd"
      BRANCH_NAME: "main"
      WORKFLOW_ID: "cloud-e2e.yml"
      APECD_REF: "main"
      EXTRA_ARGS: "TEST_TYPE=openapi-test#TEST_ENGINES=mysql#CLOUD_ENV_NAME=dev#CLOUD_BRANCH=main#GO_VERSION=1.22"
    secrets: inherit
