name: Cloud Cluster Clear

on:
  workflow_dispatch:
    inputs:
      cloud_env_name:
        description: "The cloud env name"
        type: choice
        required: true
        default: 'idc1'
        options:
          - idc
          - idc1
          - idc2
          - idc4
      cloud_org_name:
        description: "The cloud org name"
        type: choice
        required: true
        default: 'e2e-test'
        options:
          - e2e-test
          - e2e-web
      cloud_version:
        description: "The cloud release version"
        type: string
        required: true
        default: ''
  workflow_call:
    inputs:
      cloud_env_name:
        description: "The cloud env name"
        type: string
        required: true
        default: 'idc1'
      cloud_org_name:
        description: "The cloud org name"
        type: string
        required: true
        default: 'e2e-test'
      cloud_version:
        description: "The cloud release version"
        type: string
        required: true
        default: ''

run-name: Cloud Cluster Clear on Env:${{ inputs.cloud_env_name }} Org:${{ inputs.cloud_org_name }} ${{ inputs.cloud_version }}

env:
  IDC_KUBECONFIG: ${{ secrets.IDC_KUBECONFIG }}
  IDC_KUBECONFIG_1: ${{ secrets.IDC_KUBECONFIG_1 }}
  IDC_KUBECONFIG_2: ${{ secrets.IDC_KUBECONFIG_2 }}
  IDC_KUBECONFIG_4: ${{ secrets.IDC_KUBECONFIG_4 }}
  GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}


jobs:
  e2e-cluster-clear:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout testinfra Code
        uses: actions/checkout@v4
        with:
          repository: apecloud/testinfra
          path: ./
          token: ${{ env.GH_TOKEN }}

      - name: Configure ACK Context ${{ inputs.cloud_env_name }}
        id: cloud_env
        run: |
          mkdir -p $HOME/.kube
          touch $HOME/.kube/config
          CLOUD_ENV_NAME="${{ inputs.cloud_env_name }}"
          echo CLOUD_ENV_NAME="$CLOUD_ENV_NAME" >> $GITHUB_ENV
          
          E2E_ENV_VARS=""
          case "$CLOUD_ENV_NAME" in
              idc)
                  echo '${{ env.IDC_KUBECONFIG }}' > $HOME/.kube/config
                  E2E_ENV_VARS="${{ vars.E2E_ENV_VARS_IDC }}"
              ;;
              idc1)
                  echo '${{ env.IDC_KUBECONFIG_1 }}' > $HOME/.kube/config
                  E2E_ENV_VARS="${{ vars.E2E_ENV_VARS_IDC1 }}"
              ;;
              idc2)
                  echo '${{ env.IDC_KUBECONFIG_2 }}' > $HOME/.kube/config
                  E2E_ENV_VARS="${{ vars.E2E_ENV_VARS_IDC2 }}"
              ;;
              idc4)
                  echo '${{ env.IDC_KUBECONFIG_4 }}' > $HOME/.kube/config
                  E2E_ENV_VARS="${{ vars.E2E_ENV_VARS_IDC4 }}"
              ;;
          esac
          echo E2E_ENV_VARS="$E2E_ENV_VARS" >> $GITHUB_ENV

      - name: clear e2e backup
        continue-on-error: true
        run: |
          backup_filter="$(date +%Y-%m)"
          echo "delete e2e Retain backup"
          kubectl get backup -n kubeblocks-cloud-ns --no-headers | (grep "e2e-" | grep -v "${backup_filter}" || true) | awk '{print $1}' | xargs kubectl delete backup -n kubeblocks-cloud-ns &
          
          echo "patch e2e Deleting backup finalizers"
          for i in $(seq 1 10); do
              e2e_deleting_backup=$(kubectl get backup -n kubeblocks-cloud-ns --no-headers | (grep "e2e-" | grep "Deleting" || true) | awk '{print $1}')
              if [[ -z "${e2e_deleting_backup}" ]]; then
                  break
              else
                  kubectl get backup -n kubeblocks-cloud-ns --no-headers | (grep "e2e-" | grep "Deleting" || true) | awk '{print $1}' | xargs kubectl patch backup -p '{"metadata":{"finalizers":[]}}' --type=merge -n kubeblocks-cloud-ns
              fi
              sleep 1
          done

      - name: run e2e clear cluster
        run: |
          run_file_log="run_e2e_clear_result.log"
          touch ${run_file_log} 
          
          for env_vars in $(echo "${E2E_ENV_VARS}" | sed 's/|/ /g'); do
              eval_cmd="export $env_vars"
              echo "$eval_cmd"
              eval "$eval_cmd"
          done
          echo "export KB_CLOUD_TEST_ORG=${{ inputs.cloud_org_name }}"
          export KB_CLOUD_TEST_ORG=${{ inputs.cloud_org_name }}
          
          CLOUD_TEST_ENV="${{ inputs.cloud_env_name }}"
          if [[ -n "${CLOUD_TEST_ENV}" ]]; then
              echo "export KB_CLOUD_TEST_ENVIRONMENT=${CLOUD_TEST_ENV}"
              export KB_CLOUD_TEST_ENVIRONMENT="${CLOUD_TEST_ENV}"
              echo "export KB_CLOUD_TEST_NODE=node3"
              export KB_CLOUD_TEST_NODE="node3"
          fi
          
          # run e2e clear cluster
          bash test/cloud/test_cloud_e2e_clear.sh \
              --release-version "${{ inputs.cloud_version }}" \
              --env "${CLOUD_TEST_ENV}" | tee -a ${run_file_log}
          
          CLOUD_E2E_CLEAR_POD_NAME="$(cat ${run_file_log} | (grep '\[CLOUD-E2E-CLEAR-POD-NAME\]' || true) )"
          if [[ -n "${CLOUD_E2E_CLEAR_POD_NAME}" && "$CLOUD_E2E_CLEAR_POD_NAME" == "[CLOUD-E2E-CLEAR-POD-NAME]"* ]]; then
              CLOUD_E2E_CLEAR_POD_NAME=${CLOUD_E2E_CLEAR_POD_NAME#*"[CLOUD-E2E-CLEAR-POD-NAME]"}      
          fi
          echo CLOUD_E2E_CLEAR_POD_NAME="$CLOUD_E2E_CLEAR_POD_NAME" >> $GITHUB_ENV

      - name: Waiting for Cloud E2E Clear Pod to be Completed
        run: |
          set +e
          set -o nounset
          sleep 2
          while true; do
              if kubectl get pods -n default | grep "${CLOUD_E2E_CLEAR_POD_NAME}" | egrep "Completed|Error" ; then
                  echo "Cloud E2E Clear is Done"
          
                  set +e
                  set -o nounset
                  for i in $(seq 1 10); do
                      kubectl logs -n default ${CLOUD_E2E_CLEAR_POD_NAME} 
                      log_ret=$?
                      if [[ $log_ret -eq 0 ]]; then
                          break
                      fi
                      sleep 1
                  done
                  
                  for i in $(seq 1 10); do
                      kubectl delete pod -n default ${CLOUD_E2E_CLEAR_POD_NAME} --force
                      delete_ret=$?
                      if [[ $delete_ret -eq 0 ]]; then
                          break
                      fi
                      sleep 1
                  done
                  set -e
          
                  break
              fi
              if kubectl get pods -n default | grep "${CLOUD_E2E_CLEAR_POD_NAME}" | egrep "Running|Error" ; then
                  kubectl logs -n default ${CLOUD_E2E_CLEAR_POD_NAME} --tail=5
              else
                  echo "Waiting for Cloud E2E Clear Pod to be Completed..."
              fi
              sleep 1
          done

