name: Delete Actions Cache

on:
  workflow_dispatch:
    inputs:
      CACHE_KEY:
        description: "The cache key to delete"
        type: string
        required: true
        default: ''
      APECD_REF:
        description: "The branch name of apecloud-cd"
        type: string
        required: false
        default: 'main'

env:
  GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  delete-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout apecloud-cd Code
        uses: actions/checkout@v4
        with:
          repository: apecloud/apecloud-cd
          path: apecloud-cd
          ref: ${{ inputs.APECD_REF }}

      - name: delete actions cache
        continue-on-error: true
        run: |
          bash apecloud-cd/.github/utils/utils.sh \
            --type 30 \
            --github-repo "${{ github.repository }}" \
            --tag-name "${{ inputs.CACHE_KEY }}"
