name: Deploy Cloud

on:
  workflow_call:
    inputs:
      CLOUD_ENV_NAME:
        description: "The cloud env name of deploy"
        type: string
        required: false
        default: ''
      VERSION:
        description: "The tag name of image"
        type: string
        required: false
        default: ''
      KUBECTL_VERSION:
        description: "Install the specify version of kubectl (default: v1.28.3)"
        type: string
        required: false
        default: 'v1.28.3'
      REMOVE_PREFIX:
        description: "Enable remove prefix v (default: true)"
        type: boolean
        required: false
        default: true
      APECD_REF:
        description: "The branch name of apecloud-cd"
        type: string
        required: false
        default: 'main'
      UPGRADE_ADDON:
        description: "Upgrade addon (default: false)"
        type: boolean
        required: false
        default: false
      UPGRADE_ADDON_EXTRA_ENV:
        description: "The cloud env name of upgrade addon extra"
        type: string
        required: false
        default: ''


env:
  ACK_KUBECONFIG_DEV: ${{ secrets.ACK_KUBECONFIG_DEV }}
  IDC_KUBECONFIG: ${{ secrets.IDC_KUBECONFIG }}
  IDC_KUBECONFIG_1: ${{ secrets.IDC_KUBECONFIG_1 }}
  IDC_KUBECONFIG_2: ${{ secrets.IDC_KUBECONFIG_2 }}
  IDC_KUBECONFIG_4: ${{ secrets.IDC_KUBECONFIG_4 }}
  VKE_KUBECONFIG: ${{ secrets.VKE_KUBECONFIG }}
  VKE_KUBECONFIG_22: ${{ secrets.VKE_KUBECONFIG_22 }}
  VKE_KUBECONFIG_23: ${{ secrets.VKE_KUBECONFIG_23 }}
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  CLOUD_ENV_NAME: ${{ inputs.CLOUD_ENV_NAME }}
  RELEASE_VERSION: ${{ inputs.VERSION }}
  DEPLOY_RESULT: 0
  HELM_VERSION: "v3.16.3"
  JIHULAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
  JIHULAB_ACCESS_USER: ${{ secrets.GITLAB_ACCESS_USER }}
  CHART_PROJECT_ID: ${{ secrets.GITLAB_PROJECT_ID }}


jobs:
  deploy-cloud:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    outputs:
      tag-name: ${{ steps.get_tag_name.outputs.tag_name }}
      cloud-env-name: ${{ steps.cloud_env.outputs.cloud_env_name }}
      content-result: ${{ steps.deploy_result.outputs.content_result }}
    steps:
      - name: Checkout testinfra Code
        uses: actions/checkout@v4
        with:
          repository: apecloud/testinfra
          path: ./
          token: ${{ env.GITHUB_TOKEN }}

      - uses: azure/setup-kubectl@v3
        with:
          version: "${{ inputs.KUBECTL_VERSION }}"

      - name: remove v prefix
        id: get_tag_name
        shell: bash
        run: |
          tag_name="${{ inputs.VERSION }}"
          if [[ "$tag_name" == "v"* && "${{ inputs.REMOVE_PREFIX }}" == "true" ]]; then
              tag_name="${tag_name/v/}"
          fi
          echo tag_name=$tag_name >> $GITHUB_OUTPUT

      - name: Configure Context ${{ inputs.CLOUD_ENV_NAME }}
        id: cloud_env
        run: |
          mkdir -p $HOME/.kube
          touch $HOME/.kube/config
          CLOUD_ENV_NAME="${{ inputs.CLOUD_ENV_NAME }}"
          echo 'CLOUD_ENV_NAME='${CLOUD_ENV_NAME} >> $GITHUB_ENV
          echo 'cloud_env_name='${CLOUD_ENV_NAME} >> $GITHUB_OUTPUT
          case "$CLOUD_ENV_NAME" in
              dev)
                  echo '${{ env.ACK_KUBECONFIG_DEV }}' > $HOME/.kube/config
              ;;
              idc)
                  echo '${{ env.IDC_KUBECONFIG }}' > $HOME/.kube/config
              ;;
              idc1)
                  echo '${{ env.IDC_KUBECONFIG_1 }}' > $HOME/.kube/config
              ;;
              idc2)
                  echo '${{ env.IDC_KUBECONFIG_2 }}' > $HOME/.kube/config
              ;;
              idc4)
                  echo '${{ env.IDC_KUBECONFIG_4 }}' > $HOME/.kube/config
              ;;
              vke)
                  echo '${{ env.VKE_KUBECONFIG }}' > $HOME/.kube/config
              ;;
              vke22)
                  echo '${{ env.VKE_KUBECONFIG_22 }}' > $HOME/.kube/config
              ;;
              vke23)
                  echo '${{ env.VKE_KUBECONFIG_23 }}' > $HOME/.kube/config
              ;;
              *)
                  echo '${{ env.ACK_KUBECONFIG }}' > $HOME/.kube/config
              ;;
          esac
          chmod 600 $HOME/.kube/config

      - name: Create Deploy Pod
        run: |
          run_file_log="run_deploy_result.log"
          touch ${run_file_log}

          export JIHULAB_ACCESS_USER="${{ env.JIHULAB_ACCESS_USER }}"
          export JIHULAB_ACCESS_TOKEN="${{ env.JIHULAB_ACCESS_TOKEN }}"

          bash test/cloud/test_cloud_deploy.sh \
              --release-version "${{ inputs.VERSION }}" \
              --env "${{ inputs.CLOUD_ENV_NAME }}" | tee -a ${run_file_log}

          CLOUD_DEPLOY_POD_NAME="$(cat ${run_file_log} | (grep '\[CLOUD-DEPLOY-POD-NAME\]' || true) )"
          if [[ -n "${CLOUD_DEPLOY_POD_NAME}" && "$CLOUD_DEPLOY_POD_NAME" == "[CLOUD-DEPLOY-POD-NAME]"* ]]; then
              CLOUD_DEPLOY_POD_NAME=${CLOUD_DEPLOY_POD_NAME#*"[CLOUD-DEPLOY-POD-NAME]"}
          fi
          echo CLOUD_DEPLOY_POD_NAME="$CLOUD_DEPLOY_POD_NAME" >> $GITHUB_ENV

      - name: Waiting for Cloud Deploy Pod to be Completed
        run: |
          set +e
          set -o nounset
          sleep 2
          while true; do
              if kubectl get pods -n kb-cloud | grep "${CLOUD_DEPLOY_POD_NAME}" | egrep "Completed|Error" ; then
                  echo "Cloud Deploy is Done"

                  set +e
                  set -o nounset
                  for i in $(seq 1 10); do
                      kubectl logs -n kb-cloud ${CLOUD_DEPLOY_POD_NAME}
                      log_ret=$?
                      if [[ $log_ret -eq 0 ]]; then
                          break
                      fi
                      sleep 1
                  done

                  pod_phase=$(kubectl get pod -n kb-cloud ${CLOUD_DEPLOY_POD_NAME} -o jsonpath='{.status.phase}')
                  pod_status=$(kubectl get pod -n kb-cloud ${CLOUD_DEPLOY_POD_NAME} | (grep "${CLOUD_DEPLOY_POD_NAME}" || true))
          
                  if [[ "$pod_phase" == "Succeeded" || "${pod_status}" == *"Completed"* ]]; then
                      DEPLOY_RESULT=1
                      echo "DEPLOY_RESULT:${DEPLOY_RESULT}"
                      echo DEPLOY_RESULT=${DEPLOY_RESULT} >> $GITHUB_ENV
                  else
                      echo "Cloud Deploy failed, last logs:"
                      echo "==================== pod ${CLOUD_DEPLOY_POD_NAME} logs ===================="
                      kubectl logs -n kb-cloud ${CLOUD_DEPLOY_POD_NAME} --tail=100 || true
                      echo ""
                  fi

                  for i in $(seq 1 10); do
                      kubectl delete pod -n kb-cloud ${CLOUD_DEPLOY_POD_NAME} --force
                      delete_ret=$?
                      if [[ $delete_ret -eq 0 ]]; then
                          break
                      fi
                      sleep 1
                  done
                  set -e

                  [[ "${DEPLOY_RESULT}" == "1" ]] || exit 1

                  break
              fi
              if kubectl get pods -n kb-cloud | grep "${CLOUD_DEPLOY_POD_NAME}" | egrep "Running|Error" ; then
                  kubectl logs -n kb-cloud ${CLOUD_DEPLOY_POD_NAME} --tail=5
              else
                  echo "Waiting for Cloud Deploy Pod to be Completed..."
              fi
              sleep 1
          done

      - name: deploy result
        if: ${{ always() }}
        id: deploy_result
        run: |
          CONTENT="error"
          if [[ "${DEPLOY_RESULT}" == "1" ]]; then
              CONTENT="success"
          fi
          echo 'content_result='$CONTENT >> $GITHUB_OUTPUT

  send-message:
    needs: [ deploy-cloud ]
    if: ${{ always() }}
    uses: ./.github/workflows/feishui-message.yml
    with:
      TYPE: "2"
      CONTENT: "deploy ${{ needs.deploy-cloud.outputs.cloud-env-name }} release ${{ needs.deploy-cloud.outputs.tag-name }} ${{ needs.deploy-cloud.outputs.content-result }}"
      WAIT_TIME: 60
      APECD_REF: ${{ inputs.APECD_REF }}
    secrets: inherit

  trigger-deploy-cloud:
    if: ${{ (startsWith(inputs.VERSION, 'v2.2') || startsWith(inputs.VERSION, 'v2.3')) && startsWith(inputs.CLOUD_ENV_NAME, 'idc') }}
    uses: ./.github/workflows/trigger-workflow.yml
    with:
      GITHUB_REPO: "apecloud/apecloud-cd"
      BRANCH_NAME: "${{ inputs.APECD_REF }}"
      WORKFLOW_ID: "deploy-cloud-2.yml"
      APECD_REF: "${{ inputs.APECD_REF }}"
      EXTRA_ARGS: "VERSION=${{ inputs.VERSION }}#CLOUD_ENV_NAME=vke${{ startsWith(inputs.VERSION, 'v2.2') && '22' || '23' }}#UPGRADE_ADDON=true"
    secrets: inherit

  upgrade-addon:
    if: ${{ inputs.UPGRADE_ADDON && startsWith(inputs.CLOUD_ENV_NAME, 'idc') }}
    permissions:
      contents: 'read'
      id-token: 'write'
    needs: [ deploy-cloud ]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Checkout apecloud-cd Code
        uses: actions/checkout@v4
        with:
          repository: apecloud/apecloud-cd
          path: ./apecloud-cd
          ref: ${{ inputs.APECD_REF }}

      - uses: azure/setup-kubectl@v3
        with:
          version: "${{ inputs.KUBECTL_VERSION }}"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Configure Context ${{ inputs.CLOUD_ENV_NAME }}
        run: |
          mkdir -p $HOME/.kube
          touch $HOME/.kube/config
          CLOUD_ENV_NAME="${{ inputs.CLOUD_ENV_NAME }}"
          case "$CLOUD_ENV_NAME" in
              dev)
                  echo '${{ env.ACK_KUBECONFIG_DEV }}' > $HOME/.kube/config
              ;;
              idc)
                  echo '${{ env.IDC_KUBECONFIG }}' > $HOME/.kube/config
              ;;
              idc1)
                  echo '${{ env.IDC_KUBECONFIG_1 }}' > $HOME/.kube/config
              ;;
              idc2)
                  echo '${{ env.IDC_KUBECONFIG_2 }}' > $HOME/.kube/config
              ;;
              idc4)
                  echo '${{ env.IDC_KUBECONFIG_4 }}' > $HOME/.kube/config
              ;;
              vke)
                  echo '${{ env.VKE_KUBECONFIG }}' > $HOME/.kube/config
              ;;
              vke22)
                  echo '${{ env.VKE_KUBECONFIG_22 }}' > $HOME/.kube/config
              ;;
              vke23)
                  echo '${{ env.VKE_KUBECONFIG_23 }}' > $HOME/.kube/config
              ;;
              *)
                  echo '${{ env.ACK_KUBECONFIG }}' > $HOME/.kube/config
              ;;
          esac
          chmod 600 $HOME/.kube/config

      - name: Upgrade Addon
        run: |
          MANIFESTS_FILE="./manifests/deploy-manifests.yaml"
          bash ${{ github.workspace }}/apecloud-cd/.github/utils/manifests_charts_addon_upgrade.sh "${MANIFESTS_FILE}"


  upgrade-addon-idc:
    if: ${{ inputs.UPGRADE_ADDON && inputs.UPGRADE_ADDON_EXTRA_ENV != '' }}
    permissions:
      contents: 'read'
      id-token: 'write'
    needs: [ deploy-cloud ]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Checkout apecloud-cd Code
        uses: actions/checkout@v4
        with:
          repository: apecloud/apecloud-cd
          path: ./apecloud-cd
          ref: ${{ inputs.APECD_REF }}

      - uses: azure/setup-kubectl@v3
        with:
          version: "${{ inputs.KUBECTL_VERSION }}"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Configure Context ${{ inputs.UPGRADE_ADDON_EXTRA_ENV }}
        run: |
          mkdir -p $HOME/.kube
          touch $HOME/.kube/config
          CLOUD_ENV_NAME="${{ inputs.UPGRADE_ADDON_EXTRA_ENV }}"
          case "$CLOUD_ENV_NAME" in
              dev)
                  echo '${{ env.ACK_KUBECONFIG_DEV }}' > $HOME/.kube/config
              ;;
              idc)
                  echo '${{ env.IDC_KUBECONFIG }}' > $HOME/.kube/config
              ;;
              idc1)
                  echo '${{ env.IDC_KUBECONFIG_1 }}' > $HOME/.kube/config
              ;;
              idc2)
                  echo '${{ env.IDC_KUBECONFIG_2 }}' > $HOME/.kube/config
              ;;
              idc4)
                  echo '${{ env.IDC_KUBECONFIG_4 }}' > $HOME/.kube/config
              ;;
              vke)
                  echo '${{ env.VKE_KUBECONFIG }}' > $HOME/.kube/config
              ;;
              vke22)
                  echo '${{ env.VKE_KUBECONFIG_22 }}' > $HOME/.kube/config
              ;;
              vke23)
                  echo '${{ env.VKE_KUBECONFIG_23 }}' > $HOME/.kube/config
              ;;
              *)
                  echo '${{ env.ACK_KUBECONFIG }}' > $HOME/.kube/config
              ;;
          esac
          chmod 600 $HOME/.kube/config

      - name: Upgrade Addon
        run: |
          MANIFESTS_FILE="./manifests/deploy-manifests.yaml"
          bash ${{ github.workspace }}/apecloud-cd/.github/utils/manifests_charts_addon_upgrade.sh "${MANIFESTS_FILE}"
