name: ENABLE-GKE-RUNNER

on:
  workflow_call:
    inputs:
      GITHUB_REPO:
        description: "runner github repo name"
        type: string
        required: false
        default: ''
      APECD_REF:
        description: "The branch name of apecloud-cd"
        type: string
        required: false
        default: 'main'
      ENABLE:
        description: "enable flag:(enable:true)"
        type: string
        required: false
        default: 'true'
      RUNNER_LABEL:
        description: "runner label"
        type: string
        required: false
        default: ''
      RUNNER_NAMESPACE:
        description: "runner namespace"
        type: string
        required: false
        default: 'github-runner'
      RUNNER_REPLICAS:
        description: "runner replicas"
        type: number
        required: false
        default: 1
  workflow_dispatch:
    inputs:
      GITHUB_REPO:
        description: "runner github repo name"
        required: false
        default: ''
      APECD_REF:
        description: "The branch name of apecloud-cd"
        required: false
        default: 'main'
      ENABLE:
        description: "enable flag:(enable:true)"
        required: false
        default: 'true'
      RUNNER_LABEL:
        description: "runner label"
        required: false
        default: ''
      RUNNER_NAMESPACE:
        description: "runner namespace"
        required: false
        default: 'github-runner'
      RUNNER_REPLICAS:
        description: "runner replicas"
        type: number
        required: false
        default: 1


env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  CLUSTER_NAME: "infracreate-gke"
  REGION: "us-central1"

jobs:
  enable-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout apecloud-cd Code
        uses: actions/checkout@v4
        with:
          repository: apecloud/apecloud-cd
          path: ./
          ref: ${{ inputs.APECD_REF }}

      - uses: azure/setup-kubectl@v3
        with:
          version: "v1.28.3"

      - if: ${{ env.GOOGLE_CREDENTIALS != '' }}
        id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ env.GOOGLE_CREDENTIALS }}'

      - uses: simenandre/setup-gke-gcloud-auth-plugin@v1
      - uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.REGION }}

      - name: enable runner
        if: ${{ inputs.GITHUB_REPO != '' }}
        run: |
          runner_list=$(kubectl get runnerdeployments -n ${{ inputs.RUNNER_NAMESPACE }} | (grep "${{ inputs.GITHUB_REPO }}" | egrep "${{ inputs.RUNNER_LABEL }}" || true) | awk '{print $1}')
          if [[ -n "$runner_list" ]]; then
              for runner_name in $(echo "$runner_list"); do
                  echo "runner name: $runner_name"
                  hautoscalers=$(kubectl get horizontalrunnerautoscalers -n ${{ inputs.RUNNER_NAMESPACE }} | (grep "$runner_name-autoscaler" || true) )
                  if [[ "${{ inputs.ENABLE }}" == "true" ]]; then
                      echo "enable runner"
                      if [[ -n "$hautoscalers" ]]; then
                          echo "enable runner autoscaler"
                          kubectl patch horizontalrunnerautoscalers $runner_name-autoscaler -n ${{ inputs.RUNNER_NAMESPACE }} -p '{"spec":{"minReplicas": ${{ inputs.RUNNER_REPLICAS }}}}' --type=merge
                      fi
                      kubectl patch runnerdeployments $runner_name -n ${{ inputs.RUNNER_NAMESPACE }} -p '{"spec":{"replicas": ${{ inputs.RUNNER_REPLICAS }}}}' --type=merge
                  else
                      echo "disable runner"
                      if [[ -n "$hautoscalers" ]]; then
                          echo "disable runner autoscaler"
                          kubectl patch horizontalrunnerautoscalers $runner_name-autoscaler -n ${{ inputs.RUNNER_NAMESPACE }} -p '{"spec":{"minReplicas": 0}}' --type=merge
                      fi
                      kubectl patch runnerdeployments $runner_name -n ${{ inputs.RUNNER_NAMESPACE }} -p '{"spec":{"replicas": 0}}' --type=merge
                  fi
              done
          fi
