name: Issue Milestone

on:
  workflow_call:
    inputs:
      APECD_REF:
        description: "The branch name of apecloud-cd"
        type: string
        required: false
        default: 'main'


env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  issue-milestone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout apecloud-cd Code
        uses: actions/checkout@v4
        with:
          repository: apecloud/apecloud-cd
          path: apecloud-cd
          ref: ${{ inputs.APECD_REF }}

      - name: set issue milestone
        run: |
          bash ${{ github.workspace }}/apecloud-cd/.github/utils/utils.sh \
              --type 23 \
              --github-repo "${{ github.repository }}" \
              --github-token "${{ env.GITHUB_TOKEN }}" \
              --issue-number "${{ github.event.issue.number }}"
