name: KubeBlocks Addons Examples Schedule

on:
  workflow_dispatch:
  schedule:
    - cron: '30 17 * * 0-4' # Runs at 02:30 UTC on Mon to Friday

run-name: KubeBlocks Addons Examples Schedule Test on ${{ vars.CLOUD_PROVIDER }}

jobs:
  e2e_09:
    name: ${{ vars.CLOUD_PROVIDER }}
    uses: ./.github/workflows/kbcli-test-k8s.yml
    with:
      CLOUD_PROVIDER: "${{ vars.CLOUD_PROVIDER }}"
      REGION: "${{ vars.REGION_AZURE_AKS }}"
      KB_VERSION: "${{ vars.KUBEBLOCKS_VERSION_09 }}"
      TEST_TYPE: "${{ vars.KUBEBLOCKS_TEST_TYPE_09 }}"
      CLUSTER_VERSION: "1.30"
      INSTANCE_TYPE: "amd64"
      BRANCH_NAME: "main"
      ARGS: " --only-kubectl true --namespace default "
    secrets: inherit

  e2e:
    name: ${{ vars.CLOUD_PROVIDER }}
    uses: ./.github/workflows/kbcli-test-k8s.yml
    with:
      CLOUD_PROVIDER: "${{ vars.CLOUD_PROVIDER }}"
      REGION: "${{ vars.REGION_AZURE_AKS }}"
      KB_VERSION: "${{ vars.KUBEBLOCKS_VERSION }}"
      TEST_TYPE: "${{ vars.KUBEBLOCKS_TEST_TYPE }}"
      CLUSTER_VERSION: "1.30"
      INSTANCE_TYPE: "amd64"
      BRANCH_NAME: "main"
      ARGS: " --only-kubectl true --namespace default "
    secrets: inherit