name: Manifests Images Save

on:
  workflow_dispatch:
    inputs:
      MANIFESTS_FILE:
        description: "The manifests file path to save"
        type: string
        required: true
        default: ''
      VALUES_FILE:
        description: "The values file path to save"
        type: string
        required: true
        default: ''
      RELEASE_VERSION:
        description: 'The version of release'
        type: string
        required: false
        default: ''
      GITHUB_REPO:
        description: "The github repo to save"
        type: string
        required: false
        default: ''
      GITHUB_REF:
        description: "The github repo ref to save"
        type: string
        required: false
        default: 'main'
      APECD_REF:
        description: "The branch name of apecloud-cd"
        type: string
        required: false
        default: 'main'
      IMAGES_NAME:
        description: "The images package name to save"
        type: string
        required: false
        default: 'kubeblocks-enterprise'
      BOT_TYPE:
        description: 'The bot type (e.g. release/package/specify)'
        type: string
        required: false
        default: 'specify'
      BOT_WEBHOOK:
        description: 'The bot webhook'
        type: string
        required: false
        default: ''
  workflow_call:
    inputs:
      MANIFESTS_FILE:
        description: "The file path to save"
        type: string
        required: true
        default: ''
      VALUES_FILE:
        description: "The values file path to save"
        type: string
        required: true
        default: ''
      RELEASE_VERSION:
        description: 'The version of release'
        type: string
        required: false
        default: ''
      GITHUB_REPO:
        description: "The github repo to save"
        type: string
        required: false
        default: ''
      GITHUB_REF:
        description: "The github repo ref to save"
        type: string
        required: false
        default: 'main'
      APECD_REF:
        description: "The branch name of apecloud-cd"
        type: string
        required: false
        default: 'main'
      IMAGES_NAME:
        description: "The images package name to save"
        type: string
        required: false
        default: 'kubeblocks-enterprise'
      BOT_TYPE:
        description: 'The bot type (e.g. release/package/specify)'
        type: string
        required: false
        default: 'specify'
      BOT_WEBHOOK:
        description: 'The bot webhook'
        type: string
        required: false
        default: ''


run-name: save image ${{ inputs.IMAGES_NAME }} ${{ inputs.RELEASE_VERSION }}

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  OSS_KEY_ID: ${{ secrets.OSS_KEY_ID }}
  OSS_KEY_SECRET: ${{ secrets.OSS_KEY_SECRET }}
  OSS_ENDPOINT: "oss-cn-zhangjiakou.aliyuncs.com"
  OSS_BUCKET: "kubeblocks-oss"

jobs:
  save-images:
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.save-images.outputs.release-version }}
    steps:
      - name: Free disk space
        run: |
          sudo apt-get autoremove -y >/dev/null 2>&1
          sudo apt-get autoclean -y >/dev/null 2>&1
          sudo rm -rf /usr/local/lib/android >/dev/null 2>&1
          docker rmi $(docker image ls -aq) >/dev/null 2>&1
          sudo swapoff -a
          sudo rm -f /swapfile
          df -h
          
          sudo mkdir -p /mnt/new-storage
          sudo touch /etc/docker/daemon.json
          sudo tee /etc/docker/daemon.json <<EOF
          {
            "data-root": "/mnt/new-storage"
          }
          EOF
          sudo systemctl restart docker

      - name: Checkout Code
        if: ${{ inputs.GITHUB_REPO == '' }}
        uses: actions/checkout@v4

      - name: Checkout ${{ inputs.GITHUB_REPO }} Code
        if: ${{ inputs.GITHUB_REPO != '' }}
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.GITHUB_REPO }}
          path: ./
          token: ${{ env.GITHUB_TOKEN }}
          ref: ${{ inputs.GITHUB_REF }}

      - name: Checkout apecloud-cd Code
        uses: actions/checkout@v4
        with:
          repository: apecloud/apecloud-cd
          path: apecloud-cd
          token: ${{ env.GITHUB_TOKEN }}
          ref: ${{ inputs.APECD_REF }}

      - name: manifests images save
        id: save-images
        run: |
          echo "Free space:"
          df -h
          MANIFESTS_FILE="${{ inputs.MANIFESTS_FILE }}"
          VALUES_FILE="${{ inputs.VALUES_FILE }}"
          RELEASE_VERSION="${{ inputs.RELEASE_VERSION }}"
          if [[ -z "${RELEASE_VERSION}" && -f ${MANIFESTS_FILE} ]]; then
              RELEASE_VERSION="$(yq e ".kubeblocks-cloud[0].version"  ${MANIFESTS_FILE})"
          fi
          echo "release-version=${RELEASE_VERSION}" >> $GITHUB_OUTPUT
          
          echo "update manifests version to ${RELEASE_VERSION}"
          bash ${{ github.workspace }}/apecloud-cd/.github/utils/manifests_version_update.sh "${MANIFESTS_FILE}" "${RELEASE_VERSION}"
          
          echo "save manifests images"
          bash ${{ github.workspace }}/apecloud-cd/.github/utils/manifests_images_save.sh "${MANIFESTS_FILE}" "${VALUES_FILE}" "${RELEASE_VERSION}"

      - uses: manyuanrong/setup-ossutil@v2.0
        with:
          access-key-id: "${{ env.OSS_KEY_ID }}"
          access-key-secret: "${{ env.OSS_KEY_SECRET }}"
          endpoint: "${{ env.OSS_ENDPOINT }}"

      - name: Upload images to oss
        id: upload_to_oss
        run: |
          IMAGE_PKG_NAME="${{ inputs.IMAGES_NAME }}-images-${{ steps.save-images.outputs.release-version }}.tar.gz"
          ossutil cp -rf ./${IMAGE_PKG_NAME} oss://${{ env.OSS_BUCKET }}/images/${IMAGE_PKG_NAME}
          upload_ret=$?
          if [[ $upload_ret -eq 0 ]]; then
              echo "upload ${IMAGE_PKG_NAME} to oss successfully"
          else
              exit 1
          fi

  save-result:
    runs-on: ubuntu-latest
    needs: [ save-images ]
    if: ${{ always() }}
    outputs:
      image-pkg-name: ${{ steps.get_save_result.outputs.image_pkg_name }}
      save-result: ${{ steps.get_save_result.outputs.save_result }}
    steps:
      - name: get save result
        id: get_save_result
        run: |
          SAVE_RESULT="error"
          IMAGE_PKG_NAME="${{ inputs.IMAGES_NAME }}-images-${{ needs.save-images.outputs.release-version }}.tar.gz"
          if [[ "${{ needs.save-images.result }}" == "success" ]]; then
              SAVE_RESULT="success"
              IMAGE_PKG_NAME="http://kubeblocks-oss.${{ env.OSS_ENDPOINT }}/images/${IMAGE_PKG_NAME}"
          fi
          echo 'save_result='$SAVE_RESULT >> $GITHUB_OUTPUT
          echo 'image_pkg_name='${IMAGE_PKG_NAME} >> $GITHUB_OUTPUT

  send-message:
    needs: [ save-result ]
    if: ${{ always() }}
    uses: ./.github/workflows/feishui-message.yml
    with:
      TYPE: "2"
      CONTENT: "save image ${{ needs.save-result.outputs.image-pkg-name }} ${{ needs.save-result.outputs.save-result }}"
      BOT_TYPE: "${{ inputs.BOT_TYPE }}"
      BOT_WEBHOOK: "${{ inputs.BOT_WEBHOOK }}"
      APECD_REF: ${{ inputs.APECD_REF }}
    secrets: inherit
