name: Migrate Database

on:
  workflow_call:
    inputs:
      MIGRATE_PATH:
        description: "The relative path to your migration folder."
        type: string
        required: false
        default: ''
      MIGRATE_COMMAND:
        description: "The  migrate cli command to run."
        type: string
        required: false
        default: 'up'
      POSTGRESQL_VERSION:
        description: "Version of PostgreSQL to use."
        type: string
        required: false
        default: '14.12'

env:
  POSTGRESQL_USER: "postgres"
  POSTGRESQL_PASSWORD: "postgres"
  POSTGRESQL_DB: "postgres"

jobs:
  migrate:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:${{ inputs.POSTGRESQL_VERSION }}
        env:
          POSTGRES_USER: ${{ env.POSTGRESQL_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRESQL_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRESQL_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Wait for PostgreSQL
        env:
          PGPASSWORD: ${{ env.POSTGRESQL_PASSWORD }}
        run: |
          times=1
          while ! psql -U ${{ env.POSTGRESQL_USER }} -d ${{ env.POSTGRESQL_DB }} -h 127.0.0.1 --quiet -c "SELECT version()"; do
              sleep 1
              if [[ $times -gt 120 ]]; then
                  echo "PostgreSQL is not available after 120 seconds"
                  exit 1
              fi
              ((times++))
          done
        shell: bash

      - name: Migrate
        uses: vovavc/migrate-github-action@v0.2.1
        with:
          path: "${{ inputs.MIGRATE_PATH }}"
          command: "${{ inputs.MIGRATE_COMMAND }}"
          database: "postgres://${{ env.POSTGRESQL_USER }}:${{ env.POSTGRESQL_PASSWORD }}@postgres:5432/${{ env.POSTGRESQL_DB }}?sslmode=disable"
