name: Migrate Database

on:
  workflow_call:
    inputs:
      MIGRATE_PATH:
        description: "The relative path to your migration folder."
        type: string
        required: false
        default: ''
      MIGRATE_COMMAND:
        description: "The  migrate cli command to run."
        type: string
        required: false
        default: 'up'
      POSTGRESQL_VERSION:
        description: "Version of PostgreSQL to use."
        type: string
        required: false
        default: '14.12'
      POSTGRESQL_DB:
        description: "DB of PostgreSQL to use."
        type: string
        required: false
        default: 'migrate_db'
      POSTGRESQL_USER:
        description: "User of PostgreSQL to use."
        type: string
        required: false
        default: 'migrate_user'
      POSTGRESQL_PASSWORD:
        description: "Password of PostgreSQL to use."
        type: string
        required: false
        default: 'migrate_password'


jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '${{ inputs.POSTGRESQL_VERSION }}'  # See https://hub.docker.com/_/postgres for available versions
          postgresql db: '${{ inputs.POSTGRESQL_DB }}'
          postgresql user: '${{ inputs.POSTGRESQL_USER }}'
          postgresql password: '${{ inputs.POSTGRESQL_PASSWORD }}'

      - name: Wait for PostgreSQL
        env:
          PGPASSWORD: ${{ inputs.POSTGRESQL_PASSWORD }}
        run: |
          times=1
          while ! psql -U ${{ inputs.POSTGRESQL_USER }} -d ${{ inputs.POSTGRESQL_DB }} -h 127.0.0.1 --quiet -c "SELECT version()"; do
              sleep 1
              if [[ $times -gt 120 ]]; then
                  echo "PostgreSQL is not available after 120 seconds"
                  exit 1
              fi
              ((times++))
          done
        shell: bash

      - name: Migrate
        uses: vovavc/migrate-github-action@v0.2.1
        env:
          POSTGRESQL_USER: ${{ inputs.POSTGRESQL_USER }}
          POSTGRESQL_PASSWORD: ${{ inputs.POSTGRESQL_PASSWORD }}
          POSTGRESQL_DB: ${{ inputs.POSTGRESQL_DB }}
        with:
          path: "${{ inputs.MIGRATE_PATH }}"
          command: "${{ inputs.MIGRATE_COMMAND }}"
          database: "postgres://${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}@127.0.0.1:5432/${POSTGRESQL_DB}?sslmode=disable"
