name: Migrate Database

on:
  workflow_call:
    inputs:
      MIGRATE_PATH:
        description: "The relative path to your migration folder."
        type: string
        required: false
        default: ''
      MIGRATE_COMMAND:
        description: "The  migrate cli command to run."
        type: string
        required: false
        default: 'up'
      POSTGRESQL_VERSION:
        description: "Version of PostgreSQL to use."
        type: string
        required: false
        default: '14.12'

env:
  POSTGRESQL_USER: "postgres"
  POSTGRESQL_PASSWORD: "postgres"
  POSTGRESQL_DB: "postgres"

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '${{ inputs.POSTGRESQL_VERSION }}'  # See https://hub.docker.com/_/postgres for available versions
          postgresql db: '${{ env.POSTGRESQL_DB }}'
          postgresql user: '${{ env.POSTGRESQL_USER }}'
          postgresql password: '${{ env.POSTGRESQL_PASSWORD }}'

      - name: Wait for PostgreSQL
        env:
          PGPASSWORD: ${{ env.POSTGRESQL_PASSWORD }}
        run: |
          times=1
          while ! psql -U ${{ env.POSTGRESQL_USER }} -d ${{ env.POSTGRESQL_DB }} -h 127.0.0.1 --quiet -c "SELECT version()"; do
              sleep 1
              if [[ $times -gt 120 ]]; then
                  echo "PostgreSQL is not available after 120 seconds"
                  exit 1
              fi
              ((times++))
          done
        shell: bash

      - name: Migrate
        uses: vovavc/migrate-github-action@v0.2.1
        with:
          path: "${{ inputs.MIGRATE_PATH }}"
          command: "${{ inputs.MIGRATE_COMMAND }}"
          database: "postgres://postgres:postgres@127.0.0.1:5432/postgres?sslmode=disable"
