name: Pull Request Label

on:
  workflow_call:
    inputs:
      LABEL_NAME:
        description: "The name of pr label (e.g. approved)"
        type: string
        required: true
        default: ''
      LABEL_OPS:
        description: "The ops of pr label (ADD/REMOVE)"
        type: string
        required: true
        default: 'ADD'
      APECD_REF:
        description: "The branch name of apecloud-cd"
        type: string
        required: false
        default: 'main'


env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  GH_TOKEN: ${{ github.token }}

jobs:
  appprove-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout apecloud-cd Code
        uses: actions/checkout@v4
        with:
          repository: apecloud/apecloud-cd
          path: apecloud-cd
          ref: ${{ inputs.APECD_REF }}

      - name: set appprove label
        run: |
          GITHUB_TOKEN_TEP="${{ env.GITHUB_TOKEN }}"
          if [[ -z "${GITHUB_TOKEN_TEP}" ]]; then
              GITHUB_TOKEN_TEP="${{ env.GH_TOKEN }}"
          fi
          
          bash ${{ github.workspace }}/apecloud-cd/.github/utils/utils.sh \
              --type 33 \
              --github-repo "${{ github.repository }}" \
              --github-token "${GITHUB_TOKEN_TEP}" \
              --pr-number "${{ github.event.pull_request.number }}" \
              --label-name "${{ inputs.LABEL_NAME }}" \
              --label-ops "${{ inputs.LABEL_OPS }}"
