name: Pull Request Cherry Pick Usage

on:
  workflow_call:

env:
  GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  usage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout apecloud-cd Code
        uses: actions/checkout@v4
        with:
          repository: apecloud/apecloud-cd
          path: apecloud-cd
          ref: ${{ inputs.APECD_REF }}

      - name: comment issue
        run: |
          EXAMPLE_RELEASE_BRANCH="release-1.1"
          if [[ "${{ github.repository }}" == "apecloud/kubeblocks-addons" ]]; then
              EXAMPLE_RELEASE_BRANCH="release-1.0"
          elif [[ "${{ github.repository }}" == "apecloud/apecloud-addons" ]]; then
              EXAMPLE_RELEASE_BRANCH="release-0.9"
          fi
          
          bash ${{ github.workspace }}/apecloud-cd/.github/utils/utils.sh \
              --type 15 \
              --github-repo "${{ github.repository }}" \
              --issue-number "${{ github.event.pull_request.number }}" \
              --issue-comment "**Auto Cherry-pick Instructions**
          \`\`\`
          Usage:
            - /nopick: Not auto cherry-pick when PR merged.
            - /pick: release-x.x [release-x.x]: Auto cherry-pick to the specified branch when PR merged.
          
          Example:
            - /nopick
            - /pick ${EXAMPLE_RELEASE_BRANCH}
          \`\`\`"
