name: Pull Request Label Pick

on:
  workflow_call:


env:
  GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  label-pick:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout apecloud-cd Code
        uses: actions/checkout@v4
        with:
          repository: apecloud/apecloud-cd
          path: apecloud-cd

      - name: set appprove label
        run: |
          PR_NUMBER="${{ github.event.issue.number }}"
          COMMENT_BODYS="${{ github.event.comment.body }}" 
          echo "COMMENT_BODYS:${COMMENT_BODYS}"
          ADD_LABEL_NAME=""
          REMOVE_LABEL_NAME=""
          
          case "${COMMENT_BODYS}" in
              /pick)
                  ADD_LABEL_NAME="pick"
                  PR_LABELS=$(gh pr view ${PR_NUMBER} --repo ${{ github.repository }} --json labels | jq -r '.labels[].name')
                  for pr_lable in $(echo "${PR_LABELS}"); do
                      if [[ "${pr_lable}" == "nopick" || "${pr_lable}" == "pick-"* ]]; then
                          if [[ -z "${REMOVE_LABEL_NAME}" ]]; then
                              REMOVE_LABEL_NAME=${pr_lable}
                          else
                              REMOVE_LABEL_NAME="${REMOVE_LABEL_NAME},${pr_lable}"
                          fi
                      fi
                  done
              ;;
              /nopick)
                  ADD_LABEL_NAME="nopick"
                  PR_LABELS=$(gh pr view ${PR_NUMBER} --repo ${{ github.repository }} --json labels | jq -r '.labels[].name')
                  for pr_lable in $(echo "${PR_LABELS}"); do
                      if [[ "${pr_lable}" == "pick" || "${pr_lable}" == "pick-"* ]]; then
                          if [[ -z "${REMOVE_LABEL_NAME}" ]]; then
                              REMOVE_LABEL_NAME=${pr_lable}
                          else
                              REMOVE_LABEL_NAME="${REMOVE_LABEL_NAME},${pr_lable}"
                          fi
                      fi
                  done
              ;;
              /pick*)
                  if [[ "${COMMENT_BODYS}" == *"-"*"/"* || "${COMMENT_BODYS}" == *"."*"/"*  ]]; then
                      COMMENT_BODYS=$(echo "${COMMENT_BODYS}" | sed 's/\// /g')
                  elif [[ "${COMMENT_BODYS}" == *"-"*"|"* || "${COMMENT_BODYS}" == *"."*"|"* ]]; then
                      COMMENT_BODYS=$(echo "${COMMENT_BODYS}" | sed 's/|/ /g')
                  elif [[ "${COMMENT_BODYS}" == *"-"*","* || "${COMMENT_BODYS}" == *"."*","* ]]; then
                      COMMENT_BODYS=$(echo "${COMMENT_BODYS}" | sed 's/,/ /g')
                  fi
                  for comment_body in $(echo "${COMMENT_BODYS}") ; do
                      echo "comment_body:$comment_body"
                      if [[ "${comment_body}" == "pick" ]]; then
                          continue
                      fi
          
                      if [[ "${comment_body}" == "release-"* ]]; then
                          label_name_tmp="pick-${comment_body/release-/}"
                      elif [[ "${comment_body}" == "pick-"* || "${comment_body}" =~ ^([0-9]+)\.([0-9]+)$ ]]; then
                          label_name_tmp="${comment_body}"
                      fi 
          
                      if [[ -n "${label_name_tmp}" ]]; then
                          if [[ -z "${ADD_LABEL_NAME}" ]]; then
                            ADD_LABEL_NAME=${label_name_tmp}
                          else
                            ADD_LABEL_NAME="${ADD_LABEL_NAME},${label_name_tmp}"
                          fi
                      fi
                  done
          
                  PR_LABELS=$(gh pr view ${PR_NUMBER} --repo ${{ github.repository }} --json labels | jq -r '.labels[].name')
                  for pr_lable in $(echo "${PR_LABELS}"); do
                      if [[ "${pr_lable}" == "nopick" || "${pr_lable}" == "pick" || "${pr_lable}" == "pick-"* ]]; then
                          if [[ -z "${REMOVE_LABEL_NAME}" ]]; then
                              REMOVE_LABEL_NAME=${pr_lable}
                          else
                              REMOVE_LABEL_NAME="${REMOVE_LABEL_NAME},${pr_lable}"
                          fi
                      fi
                  done
              ;;
              *)
                  echo "No match found."
                  exit 1
              ;;
          esac
          echo "REMOVE_LABEL_NAME:${REMOVE_LABEL_NAME}"
          if [[ -n "${REMOVE_LABEL_NAME}" ]]; then
              bash ${{ github.workspace }}/apecloud-cd/.github/utils/utils.sh \
                  --type 33 \
                  --github-repo "${{ github.repository }}" \
                  --github-token "${{ env.GH_TOKEN }}" \
                  --pr-number "${PR_NUMBER}" \
                  --label-name "${REMOVE_LABEL_NAME}" \
                  --label-ops "REMOVE"
          
              check_remove_label=0
              for i in $(seq 1 60); do
                  sleep 1
                  PR_LABELS=$(gh pr view ${PR_NUMBER} --repo ${{ github.repository }} --json labels | jq -r '.labels[].name')
                  for pr_lable in $(echo "${PR_LABELS}"); do
                      for remove_label in $(echo "${REMOVE_LABEL_NAME} | sed 's/,/ /g'"); do
                          if [[ "${remove_label}" == "${pr_lable}" ]]; then
                              check_remove_label=1
                              break
                          fi
                      done
                  done
                  echo "checking remove label: ${PR_LABELS}"
                  if [[ ${check_remove_label} -eq 0 ]]; then
                      echo "remove label ${PR_LABELS} successfully"
                      break
                  fi
              done
          
          fi
          echo "ADD_LABEL_NAME:${ADD_LABEL_NAME}"
          bash ${{ github.workspace }}/apecloud-cd/.github/utils/utils.sh \
              --type 33 \
              --github-repo "${{ github.repository }}" \
              --github-token "${{ env.GH_TOKEN }}" \
              --pr-number "${PR_NUMBER}" \
              --label-name "${ADD_LABEL_NAME}" \
              --label-ops "ADD"
