name: Release Create

on:
  push:
    tags:
      - v*

jobs:
  release-create:
    uses: apecloud/apecloud-cd/.github/workflows/release-create.yml@main
    with:
      APECD_REF: "main"
    secrets: inherit
