name: Release Create

on:
  workflow_call:
    inputs:
      version:
        description: "The version of release"
        type: string
        required: true
        default: ''
      apecd_ref:
        description: "The ref of apecloud-cd"
        type: string
        required: false
        default: 'main'
  push:
    tags:
      - v*

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  RELEASE_VERSION: ${{ github.ref_name }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository name
        run: |
          tag_name="${{ inputs.version }}"
          if [[ -z "$tag_name" ]]; then
              tag_name=${GITHUB_REF#refs/tags/}
          fi
          repo_name=${GITHUB_REPOSITORY#*/}
          echo 'REPO_NAME='${repo_name} >> $GITHUB_ENV
          echo 'TAG_NAME='${tag_name} >> $GITHUB_ENV

      - name: release pre-release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ env.GITHUB_TOKEN }}
          name: ${{ env.REPO_NAME }} ${{ env.TAG_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          generate_release_notes: true
          prerelease: true

  send-message:
    needs: [ create-release ]
    if: ${{ failure() || cancelled() }}
    uses: ./.github/workflows/feishui-message.yml
    with:
      TYPE: "2"
      CONTENT: "create release ${{ needs.get-version.outputs.release-version }} error"
      APECD_REF: ${{ inputs.apecd_ref }}
    secrets: inherit
