name: Release Create

on:
  workflow_call:
    inputs:
      APECD_REF:
        description: "The ref of apecloud-cd"
        type: string
        required: false
        default: 'main'

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  RELEASE_VERSION: ${{ github.ref_name }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      rel-version: ${{ steps.get_rel_version.outputs.rel_version }}
    steps:
      - uses: actions/checkout@v4

      - name: Checkout apecloud-cd Code
        uses: actions/checkout@v4
        with:
          repository: apecloud/apecloud-cd
          path: apecloud-cd
          ref: ${{ inputs.APECD_REF }}

      - name: Parse release version and set REL_VERSION
        id: get_rel_version
        run: |
          python ./apecloud-cd/.github/utils/is_rc_or_stable_release_version.py
          echo rel_version=v${{ env.REL_VERSION }} >> $GITHUB_OUTPUT
          
          repo_name=${GITHUB_REPOSITORY#*/}
          echo 'REPO_NAME='${repo_name} >> $GITHUB_ENV

      - name: release pre-release without release notes
        uses: softprops/action-gh-release@v1
        if: not ${{ env.WITH_RELEASE_NOTES }}
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          name: ${{ env.REPO_NAME }} v${{ env.REL_VERSION }}
          tag_name: v${{ env.REL_VERSION }}
          generate_release_notes: true
          prerelease: true

      - name: release RC with release notes
        uses: softprops/action-gh-release@v1
        if: ${{ env.WITH_RELEASE_NOTES }}
        with:
          body_path: ./docs/release_notes/v${{ env.REL_VERSION }}/v${{ env.REL_VERSION }}.md
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          name: ${{ env.REPO_NAME }} v${{ env.REL_VERSION }}
          tag_name: v${{ env.REL_VERSION }}
          prerelease: true

  send-message:
    needs: [ create-release ]
    if: ${{ failure() || cancelled() }}
    uses: ./.github/workflows/feishui-message.yml
    with:
      TYPE: "2"
      CONTENT: "create release ${{ needs.create-release.outputs.rel-version }} error"
      APECD_REF: ${{ inputs.APECD_REF }}
    secrets: inherit
