name: Save Cache

on:
  workflow_dispatch:
    inputs:
      CACHE_KEY:
        description: 'The key of cache'
        type: string
        required: false
        default: ''
      CACHE_VALUE:
        description: 'The value of cache'
        type: string
        required: false
        default: 'true'
      APECD_REF:
        description: "The ref of apecloud-cd"
        type: string
        required: false
        default: 'main'
  workflow_call:
    inputs:
      CACHE_KEY:
        description: 'The key of cache'
        type: string
        required: false
        default: ''
      CACHE_VALUE:
        description: 'The value of cache'
        type: string
        required: false
        default: 'true'
      APECD_REF:
        description: "The ref of apecloud-cd"
        type: string
        required: false
        default: 'main'

run-name: save cache:${{ inputs.CACHE_KEY }}

env:
  GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  save-cache:
    runs-on: ubuntu-latest
    steps:
      - name: create cache file
        run: |
          ARTIFACT_KEY="${{ inputs.CACHE_KEY }}"
          touch ${ARTIFACT_KEY}
          echo "${{ inputs.CACHE_VALUE }}" > ${ARTIFACT_KEY}

      - name: Checkout apecloud-cd Code
        uses: actions/checkout@v4
        with:
          repository: apecloud/apecloud-cd
          path: apecloud-cd
          ref: ${{ inputs.APECD_REF }}

      - name: delete actions cache
        continue-on-error: true
        run: |
          bash apecloud-cd/.github/utils/utils.sh --type 30 \
            --github-repo "${{ github.repository }}" \
            --tag-name "${{ inputs.CACHE_KEY }}"

      - name: Save Artifact
        id: cache-artifact-save
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ inputs.CACHE_KEY }}
          key: ${{ inputs.CACHE_KEY }}
