name: RELEASE-IMAGE-CHECK

on:
  workflow_call:
    inputs:
      MAKE_OPS_PRE:
        description: "The pre ops name of makefile (e.g. generate)"
        type: string
        required: false
        default: ''
      IMG:
        description: "The URL to use building/pushing image targets (e.g. apecloud/kubeblocks)"
        type: string
        required: false
        default: ''
      BUILDX_PLATFORMS:
        description: "buildx platforms (default: linux/amd64,linux/arm64)"
        type: string
        required: false
        default: 'linux/amd64,linux/arm64'
      BUILDX_ARGS:
        description: "buildx args (default: --sbom=false --provenance=false)"
        type: string
        required: false
        default: ''
      GO_VERSION:
        description: "Install the specify version of GO"
        type: string
        required: false
        default: ''
      CONTEXT:
        description: "Build's context is the set of files located in the specified PATH or URL (default: .)"
        type: string
        required: false
        default: '.'
      DOCKERFILE_PATH:
        description: "Path to the Dockerfile (default: ./Dockerfile)"
        type: string
        required: false
        default: './Dockerfile'

jobs:
  release-image:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    outputs:
      tag-name: ${{ steps.get_tag_name.outputs.TAG-NAME }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:master

      - name: Setup Go
        if: inputs.GO_VERSION
        uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.GO_VERSION }}

      - name: make pre
        if: inputs.MAKE_OPS_PRE
        run: |
          make ${{ inputs.MAKE_OPS_PRE }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.CONTEXT }}
          file: ${{ inputs.DOCKERFILE_PATH }}
          platforms: ${{ inputs.BUILDX_PLATFORMS }}
          tags: ${{ inputs.IMG }}:latest
          build-args: "${{ inputs.BUILDX_ARGS }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
