name: Check Build Image

on:
  workflow_call:
    inputs:
      MAKE_OPS_PRE:
        description: "The pre ops name of makefile (e.g. generate)"
        type: string
        required: false
        default: ''
      IMG:
        description: "The URL to use building/pushing image targets (e.g. apecloud/kubeblocks)"
        type: string
        required: false
        default: ''
      BUILDX_PLATFORMS:
        description: "buildx platforms (default: linux/amd64)"
        type: string
        required: false
        default: 'linux/amd64'
      BUILDX_ARGS:
        description: "buildx args (default: --sbom=false --provenance=false)"
        type: string
        required: false
        default: ''
      GO_VERSION:
        description: "Install the specify version of GO"
        type: string
        required: false
        default: ''
      CONTEXT:
        description: "Build's context is the set of files located in the specified PATH or URL (default: .)"
        type: string
        required: false
        default: '.'
      DOCKERFILE_PATH:
        description: "Path to the Dockerfile (default: ./Dockerfile)"
        type: string
        required: false
        default: './Dockerfile'
      PYTHON_VERSION:
        description: "Install the specify version of Python"
        type: string
        required: false
        default: ''
      POETRY_VERSION:
        description: "Install the specify version of Poetry"
        type: string
        required: false
        default: ''
      ENABLE_SUBMODULE:
        description: "Enable checkout submodule  (default: false)"
        type: boolean
        required: false
        default: false

env:
  GITHUB_USER: ${{ secrets.PERSONAL_ACCESS_USER }}
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}


jobs:
  build-image:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        if: ${{ ! inputs.ENABLE_SUBMODULE }}
        uses: actions/checkout@v4

      - name: Checkout Code With Submodule
        if: ${{ inputs.ENABLE_SUBMODULE }}
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ env.GITHUB_TOKEN }}

      - name: Checkout mcp-apecloud Code
        if: ${{ contains(inputs.MAKE_OPS_PRE, 'TARGETS=apiserver') }}
        uses: actions/checkout@v4
        with:
          repository: apecloud/mcp-apecloud
          ref: main
          path: ./mcp-apecloud
          token: ${{ env.GITHUB_TOKEN }}

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:master

      - name: Setup Go
        if: inputs.GO_VERSION
        uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.GO_VERSION }}

      - name: Setup Python specify version
        if: inputs.PYTHON_VERSION
        uses: actions/setup-python@v4
        with:
          python-version: "${{ inputs.PYTHON_VERSION }}"

      - name: Setup Poetry specify version
        if: inputs.POETRY_VERSION
        uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: "${{ inputs.POETRY_VERSION }}"

      - name: make pre
        if: inputs.MAKE_OPS_PRE
        run: |
          make ${{ inputs.MAKE_OPS_PRE }}

      - name: Build without push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.CONTEXT }}
          file: ${{ inputs.DOCKERFILE_PATH }}
          platforms: ${{ inputs.BUILDX_PLATFORMS }}
          tags: ${{ inputs.IMG }}:latest
          build-args: ${{ inputs.BUILDX_ARGS }}
