name: Trivy Scan Cloud

on:
  workflow_dispatch:
    inputs:
      CLOUD_TAG:
        description: "cloud tag"
        type: string
        required: false
        default: ''
      APECD_REF:
        description: "The branch name of apecloud-cd"
        type: string
        required: false
        default: 'trivy_cloud'
  schedule:
    - cron: '0 1 * * 1' # Runs at 08:00 UTC on Mon to Friday

env:
  GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  CLOUD_REPO: "apecloud/apecloud"
  MANIFESTS_FILE: "manifests/deploy-manifests.yaml"

run-name: Trivy Scan Cloud ${{ inputs.CLOUD_TAG }}

jobs:
  get-images:
    runs-on: ubuntu-latest
    outputs:
      cloud-tag: ${{ steps.get-cloud-tag.outputs.cloud-tag }}
      kubeblocks-cloud-images: ${{ steps.get-images.outputs.kubeblocks-cloud-images }}
      kubeblocks-images: ${{ steps.get-images.outputs.kubeblocks-images }}
      gemini-images: ${{ steps.get-images.outputs.gemini-images }}
      gemini-monitor-images: ${{ steps.get-images.outputs.gemini-monitor-images }}
      ape-local-images: ${{ steps.get-images.outputs.ape-local-csi-driver-images }}
    steps:
      - name: get cloud tag
        id: get-cloud-tag
        run: |
          CLOUD_TAG="${{ inputs.CLOUD_TAG }}"
          if [[ -z "${CLOUD_TAG}" ]]; then
              CLOUD_TAG=$(gh release list --repo ${{ env.CLOUD_REPO }} | (grep "alpha" || true) | awk 'NR==1{print $2}')
          fi
          echo "cloud-tag=${CLOUD_TAG}" >> $GITHUB_OUTPUT

      - name: Checkout apecloud Code
        uses: actions/checkout@v4
        with:
          repository: ${{ env.CLOUD_REPO }}
          token: ${{ env.GH_TOKEN }}
          ref: ${{ steps.get-cloud-tag.outputs.cloud-tag }}

      - name: Checkout apecloud-cd Code
        uses: actions/checkout@v4
        with:
          repository: apecloud/apecloud-cd
          path: ./apecloud-cd
          ref: ${{ inputs.APECD_REF }}

      - name: get images
        id: get-images
        run: |
          MANIFESTS_FILE=${{ env.MANIFESTS_FILE }}
          CLOUD_TAG="${{ steps.get-cloud-tag.outputs.cloud-tag }}"
          bash apecloud-cd/.github/utils/get_scan_images.sh "${MANIFESTS_FILE}" "${CLOUD_TAG}"

  kubeblocks-cloud:
    uses: ./.github/workflows/trivy-scan.yml
    needs: [ get-images ]
    with:
      ITEM: "kubeblocks-cloud"
      IMAGES: "${{ needs.get-images.outputs.kubeblocks-cloud-images }}"
      ADDON: false
      LOGIN_DOCKER: true
    secrets: inherit

  kubeblocks:
    uses: ./.github/workflows/trivy-scan.yml
    needs: [ get-images ]
    with:
      ITEM: "kubeblocks"
      IMAGES: "${{ needs.get-images.outputs.kubeblocks-images }}"
      ADDON: false
    secrets: inherit

  gemini:
    uses: ./.github/workflows/trivy-scan.yml
    needs: [ get-images ]
    with:
      ITEM: "gemini"
      IMAGES: "${{ needs.get-images.outputs.gemini-images }}"
      ADDON: false
    secrets: inherit

  gemini-monitor:
    uses: ./.github/workflows/trivy-scan.yml
    needs: [ get-images ]
    with:
      ITEM: "gemini-monitor"
      IMAGES: "${{ needs.get-images.outputs.gemini-monitor-images }}"
      ADDON: false
    secrets: inherit

  send-message:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [ get-images, kubeblocks-cloud, kubeblocks, gemini, gemini-monitor ]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: apecloud/apecloud-cd
          path: ./

      - name: send message
        run: |
          CLOUD_TAG="${{ needs.get-images.outputs.cloud-tag }}"
          TEST_RESULT="${{ needs.kubeblocks-cloud.outputs.total-vulnerabilities }}"
          TEST_RESULT="${TEST_RESULT}##${{ needs.kubeblocks.outputs.total-vulnerabilities }}"
          TEST_RESULT="${TEST_RESULT}##${{ needs.gemini.outputs.total-vulnerabilities }}"
          TEST_RESULT="${TEST_RESULT}##${{ needs.gemini-monitor.outputs.total-vulnerabilities }}"
          
          export TZ='Asia/Shanghai'
          date_ret=$(date +%Y-%m-%d-%T)
          test_title="[${CLOUD_TAG}] Trivy Scan Vulnerabilities [${date_ret}]"
          
          send_message_url="${{ vars.CICD_WEBHOOK }}"
          
          python3 .github/utils/send_mesage.py \
              --send-type trivy-cloud \
              --url "${send_message_url}" \
              --title "$test_title" \
              --result "$TEST_RESULT"
