name: Trivy Scan Weekly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Runs at 08:00 UTC on Mon

jobs:
  elasticsearch:
    uses: ./.github/workflows/trivy-scan.yml
    with:
      ITEM: "elasticsearch"
      ADDON: true
    secrets: inherit

  influxdb:
    uses: ./.github/workflows/trivy-scan.yml
    with:
      ITEM: "influxdb"
      ADDON: true
    secrets: inherit

  llm:
    uses: ./.github/workflows/trivy-scan.yml
    with:
      ITEM: "llm"
      ADDON: true
    secrets: inherit

  loki:
    uses: ./.github/workflows/trivy-scan.yml
    with:
      ITEM: "loki"
      ADDON: true
    secrets: inherit

  mariadb:
    uses: ./.github/workflows/trivy-scan.yml
    with:
      ITEM: "mariadb"
      ADDON: true
    secrets: inherit

  milvus:
    uses: ./.github/workflows/trivy-scan.yml
    with:
      ITEM: "milvus"
      ADDON: true
    secrets: inherit

  minio:
    uses: ./.github/workflows/trivy-scan.yml
    with:
      ITEM: "minio"
      ADDON: true
    secrets: inherit

  neo4j:
    uses: ./.github/workflows/trivy-scan.yml
    with:
      ITEM: "neo4j"
      ADDON: true
    secrets: inherit

  opensearch:
    uses: ./.github/workflows/trivy-scan.yml
    with:
      ITEM: "opensearch"
      ADDON: true
    secrets: inherit

  orioledb:
    uses: ./.github/workflows/trivy-scan.yml
    with:
      ITEM: "orioledb"
      ADDON: true
    secrets: inherit

  pulsar:
    uses: ./.github/workflows/trivy-scan.yml
    with:
      ITEM: "pulsar"
      ADDON: true
    secrets: inherit

  qdrant:
    uses: ./.github/workflows/trivy-scan.yml
    with:
      ITEM: "qdrant"
      ADDON: true
    secrets: inherit

  tidb:
    uses: ./.github/workflows/trivy-scan.yml
    with:
      ITEM: "tidb"
      ADDON: true
    secrets: inherit

  victoria-metrics:
    uses: ./.github/workflows/trivy-scan.yml
    with:
      ITEM: "victoria-metrics"
      ADDON: true
    secrets: inherit

  weaviate:
    uses: ./.github/workflows/trivy-scan.yml
    with:
      ITEM: "weaviate"
      ADDON: true
    secrets: inherit

  send-message:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [ elasticsearch, influxdb, llm, loki, mariadb, milvus, minio, neo4j,
             opensearch, orioledb, pulsar, qdrant, tidb, victoria-metrics, weaviate  ]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: apecloud/apecloud-cd
          path: ./

      - name: send message
        run: |
          TEST_RESULT="${{ needs.elasticsearch.outputs.total-vulnerabilities }}"
          TEST_RESULT="${TEST_RESULT}##${{ needs.influxdb.outputs.total-vulnerabilities }}"
          TEST_RESULT="${TEST_RESULT}##${{ needs.llm.outputs.total-vulnerabilities }}"
          TEST_RESULT="${TEST_RESULT}##${{ needs.loki.outputs.total-vulnerabilities }}"
          TEST_RESULT="${TEST_RESULT}##${{ needs.mariadb.outputs.total-vulnerabilities }}"
          TEST_RESULT="${TEST_RESULT}##${{ needs.milvus.outputs.total-vulnerabilities }}"
          TEST_RESULT="${TEST_RESULT}##${{ needs.minio.outputs.total-vulnerabilities }}"
          TEST_RESULT="${TEST_RESULT}##${{ needs.neo4j.outputs.total-vulnerabilities }}"
          TEST_RESULT="${TEST_RESULT}##${{ needs.opensearch.outputs.total-vulnerabilities }}"
          TEST_RESULT="${TEST_RESULT}##${{ needs.orioledb.outputs.total-vulnerabilities }}"
          TEST_RESULT="${TEST_RESULT}##${{ needs.pulsar.outputs.total-vulnerabilities }}"
          TEST_RESULT="${TEST_RESULT}##${{ needs.qdrant.outputs.total-vulnerabilities }}"
          TEST_RESULT="${TEST_RESULT}##${{ needs.tidb.outputs.total-vulnerabilities }}"
          TEST_RESULT="${TEST_RESULT}##${{ needs.victoria-metrics.outputs.total-vulnerabilities }}"
          TEST_RESULT="${TEST_RESULT}##${{ needs.weaviate.outputs.total-vulnerabilities }}"
          
          export TZ='Asia/Shanghai'
          date_ret=$(date +%Y-%m-%d-%T)
          test_title="[Weekly] Trivy Scan Vulnerabilities [${date_ret}]"
          
          python3 .github/utils/send_mesage.py \
              --send-type trivy \
              --url "${{ vars.TEST_BOT_WEBHOOK }}" \
              --title "$test_title" \
              --result "$TEST_RESULT"