name: Update Chart Values

on:
  workflow_call:
    inputs:
      TYPE:
        description: 'Update chart type (e.g. commit|release)'
        type: string
        required: false
        default: ''
      CHART_DIR:
        description: 'Specify all charts dir'
        type: string
        required: false
        default: ''
      UPDATE_CHART:
        description: 'Specify update charts dir'
        type: string
        required: false
        default: ''
      REF_NAME:
        description: 'Ref name for update chart'
        type: string
        required: false
        default: ''
      APECD_REF:
        description: "The branch name of apecloud-cd"
        type: string
        required: false
        default: 'main'
  workflow_dispatch:
    inputs:
      TYPE:
        description: 'Update chart type (e.g. commit|release)'
        type: string
        required: false
        default: ''
      CHART_DIR:
        description: 'Specify all charts dir'
        type: string
        required: false
        default: ''
      UPDATE_CHART:
        description: 'Specify update charts dir'
        type: string
        required: false
        default: ''
      REF_NAME:
        description: 'Ref name for update chart'
        type: string
        required: false
        default: ''
      APECD_REF:
        description: "The branch name of apecloud-cd"
        type: string
        required: false
        default: 'main'

run-name: Update ${{ inputs.CHART_DIR }} ${{ inputs.UPDATE_CHART }} ${{ inputs.TYPE }}

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  update-chart-values:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: "${{ github.repository }}"
          path: ./
          token: ${{ env.GITHUB_TOKEN }}

      - name: Checkout apecloud-cd Code
        uses: actions/checkout@v4
        with:
          repository: apecloud/apecloud-cd
          path: apecloud-cd
          token: ${{ env.GITHUB_TOKEN }}
          ref: ${{ inputs.APECD_REF }}

      - name: update chart values
        id: update-chart-values
        run: |
          update_cmd="bash apecloud-cd/.github/utils/update_chart_values.sh "
          BASE_VALUES=""
          UPDATE_TYPE="${{ inputs.TYPE }}"
          CHART_DIR="${{ inputs.CHART_DIR }}"
          UPDATE_CHART="${{ inputs.UPDATE_CHART }}"
          REF_NAME="${{ inputs.REF_NAME }}"
          
          if [[ -n "${UPDATE_TYPE}" ]]; then
              update_cmd="${update_cmd} --type ${UPDATE_TYPE} "
          
              BASE_VALUES="apecloud-cd/chart-values/${UPDATE_TYPE}-values.yaml"
          fi
          
          if [[ -n "${BASE_VALUES}" && -f "${BASE_VALUES}" ]]; then
              update_cmd="${update_cmd} --base-values ${BASE_VALUES} "
          fi
          
          if [[ -n "${CHART_DIR}" ]]; then
              update_cmd="${update_cmd} --chart-dir \"${CHART_DIR}\" "
          fi
          
          if [[ -n "${UPDATE_CHART}" ]]; then
              update_cmd="${update_cmd} --update-chart \"${UPDATE_CHART}\" "
          fi
          
          if [[ -n "${REF_NAME}" ]]; then
              update_cmd="${update_cmd} --ref-name \"${REF_NAME}\" "
          fi
          
          echo "${update_cmd}"
          eval "${update_cmd}"

          if [[ "${UPDATE_TYPE}" == "commit" ]]; then
              git fetch --prune --unshallow
              git config user.name "$GITHUB_ACTOR"
              git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
              COMMIT_SHA=$(git rev-parse HEAD)
            
              FILE_CHANGES=`git diff --name-only ${COMMIT_SHA}`
              if [[ -n "$FILE_CHANGES" ]]; then
                  echo "FILE_CHANGES:"$FILE_CHANGES
                  git config --local user.name "$GITHUB_ACTOR"
                  git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
                  git commit -a -m "chore: auto update values commit info"
              fi
              echo file_changes=$FILE_CHANGES >> $GITHUB_OUTPUT
          fi

      - name: Push chart changes
        uses: ad-m/github-push-action@master
        if: ${{ inputs.TYPE == 'commit' && steps.update-chart-values.outputs.file_changes != '' }}
        with:
          directory: ./
          github_token: ${{ env.GITHUB_TOKEN }}
          repository: "${{ github.repository }}"
